---
title: "hw-03-KashyapNadendla"
format: html
editor: visual
---

## SETUP

```{r}

if(!require(pacman))
  install.packages("pacman")

pacman::p_load(tidyverse, rpart, rpart.plot, caret, 
  lattice, FSelector, sampling, pROC, mlbench)
```

## Loading Birdfeeder dataset

```{r warning=FALSE,message=FALSE}

owid_energy <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-06-06/owid-energy.csv')

```

```{r}

summary(owid_energy)
```

## Decision Trees

```{r}


owid_energy <- drop_na(owid_energy)

tree_default <- owid_energy |>
  rpart( owid_energy$gdp~.,data=_)
tree_default
```

### **Create Tree With Default Settings (uses pre-pruning)**

```{r}

library(rpart.plot)
rpart.plot(tree_default, extra = 1)
```

### **Create a Full Tree**

```{r}

tree_colors <- c("gray", "green", "blue", "brown", "orange", "red", "purple")

tree_full <- owid_energy |> 
  rpart(gdp ~ . , data = _, 
        control = rpart.control(minsplit = 2, cp = 0))
rpart.plot(tree_full, extra = 1, 
           roundint=FALSE,
            box.palette = tree_colors) # specify 7 colors
```

```{r}

tree_full
```

Training error on tree with pre-pruning

```{r}

predict(tree_default, owid_energy) |> head ()
```

```{r}

pred <- predict(tree_default, owid_energy, owid_energy)
head(pred)
```

```{r}

```
